# Generated by Django 3.2.3 on 2021-06-10 14:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import manuscripts.models
import manuscripts.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manuscript',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('CS', 'Computer Science'), ('E', 'Economics'), ('EE', 'Electrical Engineering'), ('M', 'Mathematics'), ('P', 'Physics'), ('B', 'Biology'), ('F', 'Finance'), ('S', 'Statistics'), ('O', 'Unknown')], default='O', max_length=2)),
                ('file', models.FileField(upload_to=manuscripts.models.file_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf']), manuscripts.validators.validate_file_size])),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
